version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sql-editor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      # These match the .env values in apps/be/.env
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - ./infra/postgres/init-db:/docker-entrypoint-initdb.d # Mount init script directory
      - postgres_data:/var/lib/postgresql/data # Persist data in a volume
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Named volume for PostgreSQL data
